"""Second

Revision ID: 1e7d7e7f0834
Revises: e462bded2406
Create Date: 2023-04-01 23:12:21.521515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7d7e7f0834'
down_revision = 'e462bded2406'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('microblog posts', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'microblog posts', 'user', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'microblog posts', type_='foreignkey')
    op.drop_column('microblog posts', 'user')
    op.drop_table('user')
    # ### end Alembic commands ###
